version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "12:00"
    timezone: "Europe/Zurich"
  commit-message:
    prefix: chore
    include: scope

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  commit-message:
    prefix: chore
    include: scope
  ignore:
  - dependency-name: django
    versions:
    - ">=3.3"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  commit-message:
    prefix: chore
    include: scope
  ignore:
  - dependency-name: python
    versions:
    - ">=3.10"

- package-ecosystem: npm
  directory: "/ember"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  versioning-strategy: increase
  commit-message:
    prefix: chore
    include: scope
  ignore:
    # mirror part of https://github.com/projectcaluma/ember-caluma/blob/main/.github/dependabot.yaml
    - dependency-name: graphql
      versions:
        - ">= 16"
