version: "3"
services:
  db:
    image: postgres:alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  api:
    image: adfinis-sygroup/mysagw
    ports:
      - "8000:8000"
    depends_on:
      - db

  caluma:
    image: projectcaluma/caluma:version-7.2.0
    build:
      context: caluma
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - VISIBILITY_CLASSES=caluma.caluma_user.visibilities.Authenticated,caluma.extensions.visibilities.MySAGWVisibility
      - PERMISSION_CLASSES=caluma.caluma_user.permissions.IsAuthenticated,caluma.extensions.permissions.MySAGWPermission
      - OIDC_USERINFO_ENDPOINT=https://mysagw.local/auth/realms/mysagw/protocol/openid-connect/userinfo
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
    depends_on:
      - db
      - keycloak

  caddy:
    restart: unless-stopped
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  keycloak:
    depends_on:
      - db
    image: jboss/keycloak:12.0.1
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_USER=keycloak
      - POSTGRES_DATABASE=keycloak
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true

  ember:
    build:
      context: ./ember/

volumes:
  dbdata:
  caddy_data:
  caddy_config:
