version: "3"
services:
  db:
    env_file: ./.envs/.production/.postgres

  api:
    env_file: ./.envs/.production/.api

  caluma:
    env_file: ./.envs/.production/.caluma

  ember:
    build:
      context: ./ember/

  caddy:
    env_file: ./.envs/.production/.caddy

  keycloak:
    env_file:
      - ./.envs/.production/.keycloak
