version: "3"
services:
  db:
    env_file: ./.envs/.production/.postgres

  api:
    env_file: ./.envs/.production/.api

  caluma:
    env_file: ./.envs/.production/.caluma

  caddy:
    env_file: ./.envs/.production/.caddy

  keycloak:
    env_file: ./.envs/.production/.keycloak

  ember:
    volumes:
      - ./.envs/.production/.ember:/.env:ro
