version: "3"

services:

  db:
    env_file: ./.envs/.staging/.postgres

  api:
    build:
      context: ./api/
    env_file: ./.envs/.staging/.api

  caluma:
    env_file: ./.envs/.staging/.caluma

  caddy:
    env_file: ./.envs/.staging/.caddy

  keycloak:
    env_file: ./.envs/.staging/.keycloak
    depends_on:
      - mail

  ember:
    build:
      args:
        OIDC_HOST: "${OIDC_HOST:?Set OIDC_HOST env variable}"

  mail:
    image: mwader/postfix-relay
    env_file: ./.envs/.staging/.mail
    restart: always

  minio:
    env_file: ./.envs/.staging/.minio

  mc:
    env_file: ./.envs/.staging/.minio
