version: "3"

services:

  db:
    env_file: ./.envs/.production/.postgres

  api:
    env_file: ./.envs/.production/.api

  caluma:
    env_file: ./.envs/.production/.caluma

  caddy:
    env_file: ./.envs/.production/.caddy

  keycloak:
    env_file: ./.envs/.production/.keycloak
    depends_on:
      - mail

  ember:
    build:
      args:
        OIDC_HOST: "${OIDC_HOST:?Set OIDC_HOST env variable}"

  mail:
    image: mwader/postfix-relay
    env_file: ./.envs/.production/.mail
    restart: always

  minio:
    env_file: ./.envs/.production/.minio

  mc:
    env_file: ./.envs/.production/.minio
