version: "3"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=mysagw
      # following option is a must to configure on production system:
      # https://hub.docker.com/_/postgres
      # - POSTGRES_PASSWORD=
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    image: adfinis-sygroup/mysagw
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      # following options are a must to configure on production system:
      # https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-SECRET_KEY
      # - SECRET_KEY=
      # https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts
      # - ALLOWED_HOSTS=
      # https://docs.djangoproject.com/en/2.1/ref/settings/#password
      # same as postgres password above
      # - DATABASE_PASSWORD=

  caluma:
    image: projectcaluma/caluma:version-7.2.0
    build:
      context: caluma
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=300
      - VISIBILITY_CLASSES=caluma.extensions.visibilities.MySAGWVisibility
      - PERMISSION_CLASSES=caluma.extensions.permissions.MySAGWPermission
      #- VISIBILITY_CLASSES=caluma.caluma_user.visibilities.Authenticated,caluma.extensions.visibilities.MySAGWVisibility
      #- PERMISSION_CLASSES=caluma.caluma_user.permissions.IsAuthenticated,caluma.extensions.permissions.MySAGWPermission
      - LANGUAGE_CODE=de
      - LANGUAGES=de,fr
    depends_on:
      - db
      - keycloak

  caddy:
    restart: unless-stopped
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN_NAME=mysagw.local
      - EMBER_PORT=80
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  keycloak:
    depends_on:
      - db
    image: jboss/keycloak:12.0.1
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_USER=keycloak
      - POSTGRES_DATABASE=keycloak
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true

volumes:
  dbdata:
  caddy_data:
  caddy_config:
