version: "3"
services:
  db:
    env_file: ./.envs/.staging/.postgres

  api:
    build:
      context: ./api/
    env_file: ./.envs/.staging/.api

  caluma:
    env_file: ./.envs/.staging/.caluma

  caddy:
    env_file: ./.envs/.staging/.caddy

  keycloak:
    env_file: ./.envs/.staging/.keycloak

  ember:
    build:
      args:
        OIDC_HOST: "${OIDC_HOST:?Set OIDC_HOST env variable}"
